--유저 테이블 생성
CREATE TABLE `GY`.`T_USER` (
	`USER_CD` INT AUTO_INCREMENT NOT NULL COMMENT '회원 코드' ,
	`USER_ID` VARCHAR(50) NOT NULL COMMENT '아이디' ,
	`USER_PW` VARCHAR(50) NOT NULL COMMENT '비밀번호' ,
	`CR_TIME` DATE NOT NULL COMMENT '생성일' ,
	`MODY_TIME` DATE NULL COMMENT '수정일' ,
	PRIMARY KEY (`USER_CD`)
) ENGINE = InnoDB;